[package]
name = "ui-components"
version.workspace = true
edition.workspace = true
description = "Reusable web components for Cardano applications"

[dependencies]
primitives = { workspace = true }
wallet-core = { workspace = true }
scss-macros = { path = "../scss-macros" }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
web-sys = { workspace = true, features = [
    "AddEventListenerOptions",
    "Blob",
    "CustomEvent",
    "CustomEventInit",
    "MouseEvent",
    "Response",
    "ShadowRoot",
    "HtmlStyleElement",
    "Url",
    "Window",
] }
js-sys = { workspace = true }
futures-signals = { workspace = true }
custom-elements = { workspace = true }
phf = { workspace = true }
tracing = { workspace = true }
