[build]
target = "index.html"
dist = "dist"

[serve]
address = "127.0.0.1"
port = 8091
open = false

[watch]
ignore = ["dist"]
watch = [
    "src",
    "../wallet-core/src",
    "../ui-components/src",
    "../ui-components/src/styles",
]
